### ISSUE TITLE
Dinosaurs despawn

### ISSUE THREAD

**Issue by PaiBir** [RagtimeGal/Dinos-n-Dodos#6]
As the dinos are wandering traders, they despawn eventually. This makes it rather hard to amass dinosaurs as each one has a time limit. I have done some research, and it looks like this could be fixed by setting their despawn timer to 0

**Comment by PaiBir** [comment]
I had dinosaurs actively despawning on me, and they only stopped after I changed their DespawnDelay to 0. Maybe something else from modifying their data like that means that they don't despawn, but ones I changed the DespawnDelay to 0 on never despawned, and the ones with Despawn Delays did despawn.

**Comment by RagtimeGal** [comment]
Odd. Not a issue in particularly looking to fix considering I am yet to run across it in all my testing both on servers and in single player and also because all evidence points towards it simply not being a bug. May be a issue on your end. I will fix it if I ever run across it, thank you.
